# Generated by Django 3.1.7 on 2022-04-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('portfolio_value', models.FloatField(default=0.0, verbose_name='Portfolio Value')),
                ('invested_value', models.FloatField(default=0.0, verbose_name='Invested Value')),
                ('day_projected_value', models.FloatField(default=0.0, verbose_name='Day Projected Value')),
                ('week_projected_value', models.FloatField(default=0.0, verbose_name='Week Projected Value')),
                ('month_projected_value', models.FloatField(default=0.0, verbose_name='Month Projected Value')),
                ('portfolio', models.TextField(default='', verbose_name='Portfolio')),
            ],
        ),
    ]
